[workspace]
channels = [
  "https://prefix.dev/meta-forge",
  "conda-forge",
]
name = "l0"
platforms = ["linux-64"]

[system-requirements]
cuda = "12.6"

[tasks]

[dependencies]
python = "3.10.*"
cuda = "12.6.*"
pytorch = { version = ">=2.6,<2.7", build = "*cuda*" }
nbagent = "*"
# agent rl
bubblewrap = ">=0.11.0,<0.12"
hydra-core = ">=1.3.2,<2"
sglang = "==0.4.6.post4"
torchao = ">=0.10.0,<0.11"
datasets = ">=3.6.0,<4"
pylance = {version = "*", channel = "conda-forge"}
partial-json-parser = "*"
vllm = "*"
omegaconf = ">=2.3.0,<3"
flash-attn = "*"
huggingface_hub = ">=0.30.2,<0.31"
cuda-python = ">=12.9.0,<13"
fastapi = ">=0.115.12,<0.116"
uvicorn = ">=0.34.3,<0.35"
config_dataclass = ">=0.1.0,<0.2"
liger-kernel = ">=0.5.10,<0.6"
ray-default = "2.46.*"

[pypi-dependencies]
google-search-results = "*"
serpapi = "*"
bio = "*"
mdit-py-plugins = "*"
mcpadapt = ">=0.0.15, <0.0.16"
torch-memory-saver = ">=0.0.5, <0.0.6"

verl = { path = "external/verl", editable = true}
l0 = { path = ".", editable = true }

[feature.dev.dependencies]
pytest = "*"
pre-commit = "*"
ruff = "*"
jupyterlab = ">=4.4.1,<5"
pytest-asyncio = "*"
pytest-profiling = ">=1.8.1,<2"
line_profiler = ">=4.2.0,<5"
pytest-xdist = ">=3.7.0,<4"

[feature.dev.pypi-dependencies]
neopyter = ">=0.3.1, <0.4"

[environments]
dev = { features = ["dev"], solve-group = "default" }
