traj_sampler:
  model_id: Qwen/Qwen2.5-7B-Instruct
  max_concurrency: 256
  max_retries: 1
  task_timeout: 600
  agent_type: nb_agent
  executor_type: remote
  remote_exec_server_url: 
    - http://{your_ip_address}:8000
  agent:
    uuid: abc
    openai_server_model:
      model_id: "qwen2"
      base_url: "http://{your_ip_address}:29999/v1"
      server_mode: sglang
    nb_agent:
      uuid: abc
      max_tokens: 32000
      max_response_length: 3192
      traj_save_storage_path: "./trajectory"
      agent_workspace: "./agent_workspace"
      agent_mode: llm
      trim_memory_mode: hard
      tool_ability: qa
      sampling_params:
        top_p: 0.9
    task_run:
      task: abc
      max_steps: 10
    log_path: "./log"
  evaluator:
    data_dir: "hf"
    save_dir: "./results/qwen2.5-7b-scafford"
    mode: "nb_agent"
    n_samples: 3
